//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFRestServicePMD.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class historialDeNotificacion
    {
        public long ID { get; set; }
        public int EMBARAZADA_ID { get; set; }
        public System.DateTime FECHA_ENVIO { get; set; }
        public int NOTIFICACION_ID { get; set; }
        public bool ENVIADO { get; set; }
        public Nullable<bool> RESPUESTA { get; set; }
        public string SEGUIMIENTO_ID { get; set; }
    
        public virtual embarazada embarazada { get; set; }
        public virtual notificacion notificacion { get; set; }
    }
}
