//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFRestServicePMD.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProgMilDiasEntities : DbContext
    {
        public ProgMilDiasEntities()
            : base("name=ProgMilDiasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<auxiliarNotificaciones> auxiliarNotificaciones { get; set; }
        public virtual DbSet<embarazada> embarazada { get; set; }
        public virtual DbSet<historialDeNotificacion> historialDeNotificacion { get; set; }
        public virtual DbSet<logDeSucesos> logDeSucesos { get; set; }
        public virtual DbSet<notificacion> notificacion { get; set; }
        public virtual DbSet<empresa> empresa { get; set; }
        public virtual DbSet<logMensajes> logMensajes { get; set; }
    
        public virtual ObjectResult<actualizarEstadoDeRespuesta_Result> actualizarEstadoDeRespuesta(Nullable<long> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<actualizarEstadoDeRespuesta_Result>("actualizarEstadoDeRespuesta", iDParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> actualizarHistorialDeNotificacion(string sEGUIMIENTO_ID, string rESPUESTA)
        {
            var sEGUIMIENTO_IDParameter = sEGUIMIENTO_ID != null ?
                new ObjectParameter("SEGUIMIENTO_ID", sEGUIMIENTO_ID) :
                new ObjectParameter("SEGUIMIENTO_ID", typeof(string));
    
            var rESPUESTAParameter = rESPUESTA != null ?
                new ObjectParameter("RESPUESTA", rESPUESTA) :
                new ObjectParameter("RESPUESTA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("actualizarHistorialDeNotificacion", sEGUIMIENTO_IDParameter, rESPUESTAParameter);
        }
    
        public virtual ObjectResult<getEmbarazada_Result> getEmbarazada(Nullable<int> dni)
        {
            var dniParameter = dni.HasValue ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getEmbarazada_Result>("getEmbarazada", dniParameter);
        }
    
        public virtual ObjectResult<getEmbarazadaLista_Result> getEmbarazadaLista()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getEmbarazadaLista_Result>("getEmbarazadaLista");
        }
    
        public virtual ObjectResult<getEmbarazadaListaConGestacionActualizada_Result> getEmbarazadaListaConGestacionActualizada(Nullable<bool> requiere_respuesta)
        {
            var requiere_respuestaParameter = requiere_respuesta.HasValue ?
                new ObjectParameter("requiere_respuesta", requiere_respuesta) :
                new ObjectParameter("requiere_respuesta", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getEmbarazadaListaConGestacionActualizada_Result>("getEmbarazadaListaConGestacionActualizada", requiere_respuestaParameter);
        }
    
        public virtual ObjectResult<getEmbarazadaListaConGestacionActualizadaBack_Result> getEmbarazadaListaConGestacionActualizadaBack(Nullable<bool> requiere_respuesta)
        {
            var requiere_respuestaParameter = requiere_respuesta.HasValue ?
                new ObjectParameter("requiere_respuesta", requiere_respuesta) :
                new ObjectParameter("requiere_respuesta", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getEmbarazadaListaConGestacionActualizadaBack_Result>("getEmbarazadaListaConGestacionActualizadaBack", requiere_respuestaParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> getExisteEmbarazada(Nullable<int> dni)
        {
            var dniParameter = dni.HasValue ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("getExisteEmbarazada", dniParameter);
        }
    
        public virtual ObjectResult<getHistorialNotificacionPorSeguimientoID_Result> getHistorialNotificacionPorSeguimientoID(string seguimiento_id)
        {
            var seguimiento_idParameter = seguimiento_id != null ?
                new ObjectParameter("seguimiento_id", seguimiento_id) :
                new ObjectParameter("seguimiento_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getHistorialNotificacionPorSeguimientoID_Result>("getHistorialNotificacionPorSeguimientoID", seguimiento_idParameter);
        }
    
        public virtual ObjectResult<getListaDeRespuestas_Result> getListaDeRespuestas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getListaDeRespuestas_Result>("getListaDeRespuestas");
        }
    
        public virtual ObjectResult<getNotificacionPorID_Result> getNotificacionPorID(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getNotificacionPorID_Result>("getNotificacionPorID", idParameter);
        }
    
        public virtual int insertNuevoRegistroEmbarazada(Nullable<int> dni, Nullable<int> mes, string telefono)
        {
            var dniParameter = dni.HasValue ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(int));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertNuevoRegistroEmbarazada", dniParameter, mesParameter, telefonoParameter);
        }
    
        public virtual int insertNuevoRegistroHistorialNotificacion(Nullable<int> embarazada_id, Nullable<int> notificacion_id, Nullable<bool> respuesta, string seguimiento_id)
        {
            var embarazada_idParameter = embarazada_id.HasValue ?
                new ObjectParameter("embarazada_id", embarazada_id) :
                new ObjectParameter("embarazada_id", typeof(int));
    
            var notificacion_idParameter = notificacion_id.HasValue ?
                new ObjectParameter("notificacion_id", notificacion_id) :
                new ObjectParameter("notificacion_id", typeof(int));
    
            var respuestaParameter = respuesta.HasValue ?
                new ObjectParameter("respuesta", respuesta) :
                new ObjectParameter("respuesta", typeof(bool));
    
            var seguimiento_idParameter = seguimiento_id != null ?
                new ObjectParameter("seguimiento_id", seguimiento_id) :
                new ObjectParameter("seguimiento_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertNuevoRegistroHistorialNotificacion", embarazada_idParameter, notificacion_idParameter, respuestaParameter, seguimiento_idParameter);
        }
    
        public virtual int insertRegistroLog(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertRegistroLog", descripcionParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> registrarRespuesta(Nullable<long> id, Nullable<bool> respuesta)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            var respuestaParameter = respuesta.HasValue ?
                new ObjectParameter("respuesta", respuesta) :
                new ObjectParameter("respuesta", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("registrarRespuesta", idParameter, respuestaParameter);
        }
    }
}
