//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFRestServicePMD.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class embarazada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public embarazada()
        {
            this.historialDeNotificacion = new HashSet<historialDeNotificacion>();
        }
    
        public int ID { get; set; }
        public int DNI { get; set; }
        public System.DateTime FECHA_INSCRIPCION { get; set; }
        public byte MES_GESTACION { get; set; }
        public string TELEFONO { get; set; }
        public int EMPRESAID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historialDeNotificacion> historialDeNotificacion { get; set; }
        public virtual empresa empresa { get; set; }
    }
}
