//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFRestServicePMD.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class notificacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public notificacion()
        {
            this.historialDeNotificacion = new HashSet<historialDeNotificacion>();
            this.notificacion1 = new HashSet<notificacion>();
            this.notificacion11 = new HashSet<notificacion>();
            this.notificacion12 = new HashSet<notificacion>();
        }
    
        public int ID { get; set; }
        public int NRO_ORDEN { get; set; }
        public string MENSAJE { get; set; }
        public byte MES_GESTACION { get; set; }
        public bool REQUIERE_RESPUESTA { get; set; }
        public Nullable<int> NOTIFICACION_ID_RESP_POS { get; set; }
        public Nullable<int> NOTIFICACION_ID_RESP_NEG { get; set; }
        public Nullable<bool> ES_RESPUESTA_DE_MENSAJE_ANTERIOR { get; set; }
        public Nullable<int> NOTIFICACION_HABILITANTE { get; set; }
        public bool ACTIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historialDeNotificacion> historialDeNotificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notificacion> notificacion1 { get; set; }
        public virtual notificacion notificacion2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notificacion> notificacion11 { get; set; }
        public virtual notificacion notificacion3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notificacion> notificacion12 { get; set; }
        public virtual notificacion notificacion4 { get; set; }
    }
}
